# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171023_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
