# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171024_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=150, null=True),
        ),
    ]
