# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-06 10:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20171103_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 25, 49, 573000, tzinfo=utc))),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
