# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-06 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171106_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 27, 2, 199000, tzinfo=utc)),
        ),
    ]
