# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171106_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
