# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-30 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_by',
            field=models.ManyToManyField(related_name='follows', to='registration.Profile'),
        ),
    ]
